apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
  namespace: wizards
spec:
  ports:
  - name: grpc
    port: 9999
    targetPort: 9999
  selector:
    name: server
  type: ClusterIP