apiVersion: v1
kind: Service
metadata:
  name: wizards-server
  labels:
    name: wizards-server
spec:
  ports:
  - name: grpc
    port: 9999
    targetPort: 9999
  selector:
    name: wizards-server
  type: ClusterIP