apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizards-client
  labels:
    name: wizards-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wizards-client
  template:
    metadata:
      labels:
        name: wizards-client
    spec:
      containers:
        - name: wizards-client
          image: wizards-client:v1
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "WIZARDS_SERVER_GRPC_PORT"
              valueFrom:
                configMapKeyRef:
                  name: "wizards-client-configmap"
                  key: "WIZARDS_SERVER_GRPC_PORT"
