apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizards-client
  labels:
    name: wizards-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wizards-client
  template:
    metadata:
      labels:
        name: wizards-client
    spec:
      containers:
        - name: wizards-client
          image: ryanthebossross/wizards-client:v1
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: wizards-client
